### ISSUE TITLE
[question]: Example seems to throw an 'app_id' not found error

### ISSUE THREAD

**Issue by EwanValentine** [OneSignal/onesignal-go-api#21] opened 2023-01-05 10:00 UTC
### How can we help?

I've pulled some of the examples from this repo, creating a 'player' and sending a notification:

```golang
func main() {
	notification := *onesignal.NewNotification("<app-id>")

	configuration := onesignal.NewConfiguration()
	apiClient := onesignal.NewAPIClient(configuration)

	appAuth := context.WithValue(context.Background(), onesignal.AppAuth, "<api-key>")

	player := *onesignal.NewPlayer("7c9b2780-c3ae-4f89-8776-64b112896aff", 0)
	resp, r, err := apiClient.DefaultApi.CreatePlayer(appAuth).Player(player).Execute()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error when calling `DefaultApi.CreatePlayer``: %v\n", err)
		fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", r)
		return
	}

	// response from `CreateNotification`: CreateNotificationSuccessResponse
	fmt.Fprintf(os.Stdout, "Response from `DefaultApi.CreateNotification`: %v\n", resp)

	notificationResp, r, err := apiClient.DefaultApi.CreateNotification(appAuth).Notification(notification).Execute()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error when calling `DefaultApi.CreateNotification``: %v\n", err)
		fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", r)
	}

	// response from `CreateNotification`: CreateNotificationSuccessResponse
	fmt.Fprintf(os.Stdout, "Response from `DefaultApi.CreateNotification`: %v\n", notificationResp)
}
```

However, this seems to throw an error:

```
{{"errors":["app_id not found. You may be missing a Content-Type: application/json header."]}}
```

I am setting the app ID, and as I'm using an SDK, I'm not sure that I can set the 'Content-Type' headers, or even need to. Any ideas what I'm doing wrong here? 

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kerrickchan** [comment] 2024-07-25 09:48
I tried work with codes below

package main

import (
	"context"
	"fmt"
	"os"

	"github.com/OneSignal/onesignal-go-api"
)

func main() {
	notification := *onesignal.NewNotification("OneSignal App ID")
	notification.IncludedSegments = []string{"All"}
	content := onesignal.NewStringMap()
	msg := "Hello, World!"
	content.En = &msg
	notification.SetContents(*content)

	configuration := onesignal.NewConfiguration()
	configuration.Debug = true
	apiClient := onesignal.NewAPIClient(configuration)

	appAuth := context.WithValue(context.Background(), onesignal.AppAuth, "OneSignal Setting Rest API Key")

	resp, r, err := apiClient.DefaultApi.CreateNotification(appAuth).Notification(notification).Execute()

	if err != nil {
		fmt.Fprintf(os.Stderr, "Error when calling `DefaultApi.CreateNotification``: %v\n", err)
		fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", r)
	}

	// response from `CreateNotification`: CreateNotificationSuccessResponse
	fmt.Fprintf(os.Stdout, "Response from `DefaultApi.CreateNotification`: %v\n", resp)
}

**Comment by jennantilla** [comment] 2024-11-01 17:24
Hello there! Apologies that this issue was missed. Since quite some time has passed since this was reported, we're going to close this issue. If you are still having trouble on the [latest release](https://github.com/OneSignal/onesignal-go-api/releases/tag/v2.0.3), please open a new issue with updated reproduction steps and we will be happy to assist!

**Closed as completed by jennantilla** 2024-11-01 17:24 UTC
